### ISSUE TITLE
Why some bridge always ask users to input private key?

### ISSUE THREAD

**Issue by zydjohnHotmail** [skalenetwork/skale-network#173]
Hello:
I want to bridge some BTCBAM tokens from its native network ‘BTCBAM’ to Ethereum (ERC20) network, so I can get some wrapped BTCBAM tokens.
I know its contract address on BSC is: 0x79abC799ae4B749C01e07a60c8687A49D128eA1C
Someone has provide the following URL for bridging the navite ‘BTCBAM’ token to Ethereum (ERC20) network. The URL is:
https://0x00c83aecc790e8a4453e5dd3b0b4b3680501a7a7.art/
I think maybe this is a unisawp or skale-network, but I am not sure.
However, the issue is: I can never connect automatically when I launch my MetaMask wallet, the web page always asks me to input private key or 12-words paraphrases.
I don't think a good bridge will ask users to input private key or paraphrases, as from my personal experience, this will result in loss of all funds in the MetaMask wallet.
My question is: if this URL is some kind of Unisawp or Skale-network bridge, then someone should fix the bug, as it always ask users to input private key or paraphrases.
By the way, I also need some advice on how to use Uniswap or Skale-network to bridge tokens as what I want to do.
Please advise,
Thanks,

**Comment by 0x534B414C452068656C706572** [comment]
**You should never trust any webpage that requests to input your private key or mnemonic.**
**Never click a link sent to you, even if it looks legit.**

https://help.myetherwallet.com/en/articles/5377928-pro-tips-how-to-avoid-phishing-scams

I do not recognize the URL you provide, nor will I ever click on a URL like that.
I don't think your discussion is even relevant for SKALE Network.

**Comment by zydjohnHotmail** [comment]
Hi,
Thanks for your reply. I want to know if I can use SKALE network to bridge tokens.  Like the BTCBAM tokens, since its network is not well-known, then how can I add a custom network (BTCBAM) if I can use SKALE network for bridging.
Please advise,
Thanks,
